dist: trusty

language: java

jdk:
  - oraclejdk8

before_install:
  - nvm install node

install:
  - npm install web-push-testing-service@0.3.2 -g

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start || echo \"Unable to start virtual display.\""
  - sleep 3

script:
  - web-push-testing-service start wpts
  - ./gradlew test
  - web-push-testing-service stop wpts
